package com.javatechie.spring.swagger.api.model;

import java.io.Serializable;

import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table
@Data
@NoArgsConstructor
public class Book implements Serializable {

	private static final long serialVersionUID = -1670893016517855654L;
	@Id
	@GeneratedValue
	@ApiModelProperty(value = "autogenerated id")
	private int bookId;
	@ApiModelProperty(value = "this is the book name")
	private String bookName;
	@ApiModelProperty(value = "this is book price")
	private double price;
}
